apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    name: db
spec:
  selector:
    name: nginx
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30006
    protocol: TCP  