apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    tier: web
spec:
  selector:
    matchLabels:
      name: nginx
  replicas: 3
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - name: nginx-application
        image: nginx:1.25.5
        ports:
        - containerPort: 80
       
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: web
  name: web
spec:
  containers:
  - image: redis
    imagePullPolicy: Always
    name: web
    resources: {}
